# Generated by Django 4.0.10 on 2026-01-21 08:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Fintness', 'Fitness'), ('Weights', 'Weights')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 digits', regex='^\\d{11}$')])),
                ('tall', models.DecimalField(decimal_places=2, max_digits=3)),
                ('weight', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app.category')),
                ('tags', models.ManyToManyField(to='app.tag')),
            ],
            options={
                'verbose_name_plural': 'Heroes',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['first_name'], name='idx_first_name'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['last_name'], name='idx_last_name'),
        ),
    ]
