# Generated by Django 4.0.10 on 2026-01-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Heroes'},
        ),
    ]
